---
- name: Install gnupg2 for external repository
  package:
    name:
      - gnupg2
  become: yes

- name: Add PHP8 repository key
  ansible.builtin.apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: Add PHP8 repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.sury.org/php/ bullseye main
    state: present

- name: Packages required for {{ vm_name }}
  package:
    name:
      - php8.0-cli
  become: yes

- name: Create script for launching the PHP interactive terminal
  ansible.builtin.copy:
    src: "{{ role_path }}/files/php-interactive"
    dest: /usr/bin/php-interactive
    owner: root
    group: root
    mode: '0755'

- name: Set interactive shell
  user:
    name: "{{ vm_standard_user }}"
    shell: /usr/bin/php-interactive
