runtime! debian.vim
syntax on
set background=dark
set tabstop=8
set shiftwidth=2
set expandtab
set softtabstop=0
set autoindent
set smarttab
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
filetype plugin indent on
set showmatch
set ignorecase
set smartcase
set incsearch
set autowrite
set hidden 
set mouse=a
